Repository HAN-MUN-CHEOL/hanmundan-aos, pull requests merged in 2023-12, with the labels that each got.

#14 my page xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sookmyung/hanmundan/ui/myPage/ChangeNickNameActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/ui/myPage/MyPageActivity.kt
  app/src/main/res/drawable/ic_dark_green_arrow.xml
  app/src/main/res/drawable/ic_feather_80.xml
  app/src/main/res/drawable/ic_feather_green.xml
  app/src/main/res/drawable/shape_green_fill_10_rectangle.xml
  app/src/main/res/layout/activity_calender.xml
  app/src/main/res/layout/activity_change_nickname.xml
  app/src/main/res/layout/activity_my_page.xml
  app/src/main/res/values/strings.xml
Labels: 강희🐬

#16 메뉴와 액티비티 연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sookmyung/hanmundan/ui/join/JoinActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/ui/joinSuccess/JoinSuccessActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/ui/main/MainActivity.kt
  app/src/main/res/drawable/ic_bookmark_blank.xml
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_join_success.xml
  app/src/main/res/layout/activity_main.xml
Labels: 민주🦄

#21 Feature/#20 main join add function
  app/src/main/java/com/sookmyung/hanmundan/ui/join/JoinActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/ui/main/MainActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/util/ToastCustom.kt
  app/src/main/res/drawable/toast_custom.xml
  app/src/main/res/layout/activity_join.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/toast_layout.xml
  app/src/main/res/values/strings.xml
Labels: 민주🦄

#26 스낵바 커스텀
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sookmyung/hanmundan/ui/join/JoinActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/ui/main/MainActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/util/SnackbarCustom.kt
  app/src/main/java/com/sookmyung/hanmundan/util/ToastCustom.kt
  app/src/main/res/drawable/snackbar_custom.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/snackbar_layout.xml
  app/src/main/res/values/strings.xml
Labels: 민주🦄

#28 회원가입 닉네임 전달
  app/src/main/java/com/sookmyung/hanmundan/ui/join/JoinActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/ui/joinSuccess/JoinSuccessActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/ui/main/MainActivity.kt
  app/src/main/res/layout/activity_join_success.xml
  app/src/main/res/layout/navigation_header.xml
  app/src/main/res/values/strings.xml
Labels: 민주🦄

#30 #23 - 퇴고하기 다이얼로그 완료(삭제 기능 제외)
  app/src/main/java/com/sookmyung/hanmundan/ui/rewrite/RewriteActivity.kt
  app/src/main/res/layout/activity_rewrite.xml
  app/src/main/res/layout/dialog_delete_sentence.xml
Labels: 지연🐸

#43 파이어베이스, 메인 연결
  app/build.gradle
  app/src/main/java/com/sookmyung/hanmundan/ui/main/MainActivity.kt
Labels: 민주🦄

#48 달력에서 퇴고하기로 데이터 받기, 퇴고하기 글 수정, 삭제
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/sookmyung/hanmundan/ui/main/MainActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/ui/rewrite/RewriteActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/util/SnackbarCustom.kt
  app/src/main/res/layout/activity_rewrite.xml
Labels: 민주🦄

#53 #51 메인, 퇴고 저장 상태 저장
  app/src/main/java/com/sookmyung/hanmundan/ui/main/MainActivity.kt
  app/src/main/java/com/sookmyung/hanmundan/ui/rewrite/RewriteActivity.kt
Labels: 민주🦄
